//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LatestNews.Components.UiFunctionality.Localization
 {
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LatestNews.Components.UiFunctionality.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to title for no internet connection text!!.
        /// </summary>
        public static string Dialog_InternetConnection_Title {
            get {
                return ResourceManager.GetString("Dialog_InternetConnection_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to message for no internet connection text!!.
        /// </summary>
        public static string Dialog_InternetConnection_Message {
            get {
                return ResourceManager.GetString("Dialog_InternetConnection_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ok text!!.
        /// </summary>
        public static string Dialog_OK_Text {
            get {
                return ResourceManager.GetString("Dialog_OK_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to mpty or have to be valid url Text!!.
        /// </summary>
        public static string RootViewModel_UrlNotValidText {
            get {
                return ResourceManager.GetString("RootViewModel_UrlNotValidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RootViewModel Please provide the url Text!!.
        /// </summary>
        public static string RootViewModel_EmptyEntryText {
            get {
                return ResourceManager.GetString("RootViewModel_EmptyEntryText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RootViewModel Enter the preview link Text!!.
        /// </summary>
        public static string RootViewModel_EnterPreviewLinkText {
            get {
                return ResourceManager.GetString("RootViewModel_EnterPreviewLinkText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RootViewModel Submit Text!!.
        /// </summary>
        public static string RootViewModel_SubmitButtonText {
            get {
                return ResourceManager.GetString("RootViewModel_SubmitButtonText", resourceCulture);
            }
        }

    
    }
}
